### ISSUE TITLE
Add support for private groups

### ISSUE THREAD

**Issue by kurtpa** [marcolenzo/gameboard#2]
As a gameboard user i want to be able to create private groups where i can invite my friends only and share games/stats between us

**Comment by marcolenzo** [comment]
I think this is a primary feature. I would implement it right after user registration. At this stage I am leaning towards modeling Groups as "Gameboard".

A Gameboard will have the following characteristics:
- ID
- Name
- Type (Game Type. In the future we could have pre-loaded templates. E.g. Resistance)
- Members (List of enrolled players which ends up being the request group) 
- Private vs Public (I'd leave this for later. Initially I would assume all Gameboards as Private)
- Game Type Metadata... TBD

We could have later on extra layers like Group of Friends which would speed up GameBoard creation.
