### ISSUE TITLE
User Avatars

### ISSUE THREAD

**Issue by marcolenzo** [marcolenzo/gameboard#21]

**Comment by gigadeleo** [comment]
Gender based avatars - female / male characters - as default chars
(requires gender option selection on signup or facebook data.)

**Comment by gigadeleo** [comment]
Red/Blue avatar auras or badges based on player's:
- Selection as Resistance or Spy (see #27)
  OR
- Win% as Resistance or Spy

**Comment by marcolenzo** [comment]
For now we have basic avatars. I'll expand on them later on.
